id: P52675F5F
initial_creation_type: input
source_metadata:
  title: Tsok Series
  language: es
  description: 'Lotsawa House presents the following texts related to the practice
    of tsok (tshogs) or feast-gathering (Skt. gaṇacakra):'
  volume:
    055970b736114581920ffdd5c7f5b035:
      title: Introduction to Gaṇacakra (Tsok)
      parent: Introduction
    83893f768d9e44b6b0b2b74310165894:
      title: A Concise Explanation of Gaṇacakra
      parent: Explanation
    7f031630104647349e7a9622e74682b5:
      title: 'A Bouquet of Uḍumbara Flowers: An Explanation of the Tenth Day'
      parent: Explanation
    d1777f972d7443f7b6a9ac536d9605e7:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Explanation
    a76f4915f60a4f069564a6fad4a4dea2:
      title: The Gaṇacakra Ritual
      parent: Explanation
    9bee04a63c644b4ebd094add83c80770:
      title: 'Sweet Droplets of the Honey of Accomplishment: A Concise Explanation
        of the Indispensable Points of the Feast-Gathering'
      parent: Explanation
    559306e1de1349a09bfa3fb173ff23ea:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Offering Liturgies
    6769008830234d16985526a2120eecc5:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Offering Liturgies
    a512d15a5c7e4f1999fe4349238ae2c1:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Prayers
    d88905e1426f43028305c96efc03c506:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Prayers
    d2d396c85f5b46a0912ccaab5264c0a8:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Prayers
    e110e19da6574474b06581c78c76f67e:
      title: Brief Prayer of the Feast Gathering
      parent: Prayers
    8792a472e04f483fbeb5792c26d35357:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Prayers
    b9d16cd10eca4730a97c263ce9b915e2:
      title: Food Offering Prayer
      parent: Prayers
    5492fe2cbbb3452db626ef0b62ce7ec6:
      title: Concise Tsok Feast
      parent: Prayers
    1ca4c404964f498083cdc1305db81b49:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Prayers
    45af65104fe24924bed5f0c23d44a947:
      title: A Concise Feast Prayer
      parent: Prayers
    dd1422eb202148efa6bf6c71004c0a29:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Remainder Offering
    794cb1ccc2bb41a888a11f01ad8b68ea:
      title: The Song of the Vajra
      parent: Songs
    05bde3d24d1c4ef28ee96615b0226134:
      title: 'Ḍākinī’s Delight: A Song of the Feast'
      parent: Songs
    5dbf4b662bce4765bb3073757a40b1be:
      title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the
        Tsok Feast Offering to Venerable and Exalted Vajrayoginī'
      parent: Songs
    37ce54324bf24da1a5c16b960ac20f55:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Songs
    998996ddc45f4ac3a46dfa26f603c323:
      title: Song of the Feast (Tsok Lu)
      parent: Songs
created_at: '2022-03-01T06:26:39.646591'
last_modified_at: '2022-03-01T06:26:39.646594'
